# Speisekarte des Collo, übernommen von der eigenen Website
# https://sites.google.com/view/collorestaurantbar/speisekarte (abgerufen 29.09.2026).
# Offensichtliche Tippfehler korrigiert, Preise unverändert.
# Format: (Nummer, Name, Beschreibung, Preis)

SPECIALS = [
    ("", "Saltimbocca alla Romana", "Zartes Schweinefilet mit Serranoschinken und Salbei in Marsalasauce, mit Beilagensalat und selbstgebackenem Brot", "18,30"),
    ("", "Carne alla Collo", "Feines argentinisches Roastbeef, dünn geschnitten, mit Rucola und Parmesan, pikant, mit selbstgebackenem Brot", "23,00"),
    ("", "Carpaccio", "Hauchdünn mariniertes Rindfleisch mit Rucola und Parmesan, Tomaten, mit selbstgebackenem Brot", "12,40"),
    ("", "Caprese", "Frische Tomaten, Mozzarella und Basilikum, verfeinert mit Balsamicocreme", "10,50"),
]

MENU = [
    ("tapas", "Tapas", "Klein, zum Teilen, am besten mehrere.", None, [
        ("1", "Pinchitos", "gegrillte Schweinefiletspieße", "6,50"),
        ("2", "Papas Bravas", "gebratene Kartoffeln in scharfer Tomatensauce", "5,30"),
        ("3", "Almendras Fritas", "gebratene Mandeln", "4,10"),
        ("4", "Dátiles con Bacon", "gebackene Datteln in Bacon gewickelt, mit Schafskäse gefüllt", "5,30"),
        ("5", "Gambas a la Plancha", "gegrillte Gambas", "7,70"),
        ("6", "Gambas al Ajillo", "Gambas in Olivenöl, Knoblauch, pikant", "7,70"),
        ("7", "Calamares a la Plancha", "gegrillter Tintenfisch", "5,30"),
        ("8", "Boquerones Fritos", "frittierte Sardellen", "5,30"),
        ("9", "Queso Manchego", "Käse aus La Mancha", "5,30"),
        ("10", "Jamón Serrano", "spanischer, luftgetrockneter Schinken", "5,30"),
        ("11", "Chorizo de Cana", "spanische Paprikawurst", "5,30"),
        ("12", "Salchichón", "spanische, luftgetrocknete Salami", "5,30"),
        ("13", "Aceitunas verdes y negras", "gemischte Oliven", "4,10"),
        ("14", "Alioli y Pan", "Knoblauchsauce mit selbstgemachtem Brot", "3,50"),
        ("15", "Gebackenes Hähnchen", "Hähnchenfilet in Weißweinsauce und Knoblauch", "6,50"),
        ("16", "Chorizo al Vino Tinto", "spanische Paprikawurst, gekocht in Rotwein", "5,30"),
        ("17", "Gambas im Serranomantel", "gegrillte Gambas, umwickelt von Serrano, gefüllt mit Mozzarella", "6,50"),
        ("18", "Tortilla", "spanisches Omelett mit Serrano", "4,10"),
        ("19", "Muslitos de Mar", "frittiertes Krebsfleisch", "5,30"),
        ("20", "Pimientos de Padrón", "frittierte kleine Paprikaschoten mit Meersalz", "5,30"),
        ("21", "Grüner Spargel", "gegrillter grüner Spargel, umwickelt von Serrano", "5,30"),
        ("22", "Calamares Fritos", "frittierte Calamares", "5,30"),
        ("603", "Gebratene Pilze", "mit Knoblauch", "5,30"),
        ("605", "Kartoffeln in Schinken", "gegarte Kartoffeln im Serranomantel", "5,80"),
        ("612", "Papas arrugadas con Mojo", "Runzelkartoffeln mit selbstgemachtem Mojo", "5,30"),
        ("65", "Gambas en Salsa de Tomate", "Gambas in Tomatensauce, pikant", "7,70"),
    ]),
    ("pizzabroetchen", "Pizzabrötchen", None, None, [
        ("23", "mit Tomate und Mozzarella", "", "5,30"),
        ("24", "mit Käse und Kochschinken", "", "5,00"),
        ("25", "mit Käse und Salami", "", "5,00"),
        ("26", "mit Käse und Thunfisch", "", "5,00"),
        ("27", "mit Käse", "", "4,10"),
        ("28", "ohne alles", "", "2,40"),
        ("29", "Alioli zum Dippen", "", "1,80"),
    ]),
    ("salate", "Salate", None, "Wir würzen unsere Salate mit selbstgemachter Vinaigrette, dazu servieren wir unser selbstgebackenes Brot.", [
        ("30", "Mixta", "bunter Salatteller mit Tomaten, Gurken, roten Zwiebeln und Paprika", "8,90"),
        ("31", "Ensalada Primavera", "Mixta mit Mozzarella, frischem Basilikum, Parmesansplittern und Balsamicocreme", "11,20"),
        ("32", "Ensalada de Atún", "Mixta mit Thunfisch", "11,20"),
        ("33", "Ensalada de la Casa", "Mixta mit Thunfisch, gekochtem Ei, Kochschinken und Käse", "13,00"),
        ("34", "Ensalada Granaína", "Mixta mit Thunfisch, gekochtem Ei, gemischten Oliven, grünem Spargel und Artischocken", "13,60"),
        ("35", "Ensalada de Tomates", "frische Strauchtomaten mit roten Zwiebeln, Balsamicocreme", "10,00"),
    ]),
    ("bruschetta", "Bruschetta", None, None, [
        ("36", "Bruschetta", "mit Mozzarella, frischen Tomaten und Basilikum", "8,30"),
        ("37", "Bruschetta", "mit frischen Tomaten, Rucola und Parmesan", "8,30"),
        ("38", "Bruschetta", "mit frischen Tomaten, roten Zwiebeln und Thunfisch", "8,30"),
        ("39", "Pan Catalán", "geröstetes Brot mit geriebenen Tomaten und Serranoschinken", "8,30"),
    ]),
    ("pizza", "Pizza", "Alle mit Tomatensauce und Käse.", None, [
        ("40", "Margherita", "", "8,90"),
        ("41", "Salami", "", "10,60"),
        ("42", "Jamón", "Kochschinken", "10,60"),
        ("43", "Caprese", "frische Tomaten, Mozzarella, Basilikum", "11,20"),
        ("44", "Thunfisch", "", "11,20"),
        ("45", "Chef", "Kochschinken, Pilze", "11,20"),
        ("46", "Frutti di Mare", "Meeresfrüchte", "12,40"),
        ("47", "Gladiatore", "Kochschinken, Pilze, Thunfisch", "11,80"),
        ("48", "Mexicaner", "Kochschinken, Paprika, Mais, rote Bohnen, Peperoni", "11,80"),
        ("49", "Hawaii", "Kochschinken, Ananas", "11,20"),
        ("50", "Quattro Stagioni", "Kochschinken, Pilze, Paprika, Artischocken", "11,20"),
        ("51", "Calzone", "Kochschinken, Salami, Pilze, rote Zwiebeln, Artischocken", "12,40"),
        ("52", "Mafia", "Penne Bolognese", "11,80"),
        ("53", "Collo", "argentinisches Roastbeef, rote Zwiebeln", "13,60"),
        ("54", "Vegetaria", "Brokkoli, Paprika, Spinat, Tomaten", "11,80"),
        ("55", "Gorgonzola", "frische Tomaten, Pilze, Gorgonzola", "11,80"),
        ("56", "Holandesa", "Kochschinken, grüner Spargel, Sauce Hollandaise", "11,80"),
        ("57", "Serrano y Rucola", "Rucola, Serranoschinken, frische Tomaten, Parmesansplitter", "13,60"),
        ("58", "Chorizo y Queso de Cabra", "spanische Paprikawurst, Schafskäse", "12,40"),
        ("59", "Gambas", "Gambas, Knoblauch, Petersilie", "12,40"),
        ("60", "Capone", "Kochschinken, Thunfisch, Ei", "12,40"),
        ("61", "Capricciosa", "Kochschinken, Pilze, Artischocken", "12,40"),
        ("62", "Pollo", "Hähnchenbrustfilet, Schafskäse, rote Zwiebeln, Sauce Hollandaise, Peperoni", "13,60"),
        ("63", "Grüner Spargel", "grüner Spargel, Serranoschinken, Parmesansplitter", "13,60"),
    ]),
    ("spaghetti", "Spaghetti", None, None, [
        ("70", "Napoli", "Tomatensauce und Cherrytomaten", "11,20"),
        ("71", "Bolognese", "mit selbstgemachter Fleischsauce", "13,60"),
        ("72", "Carbonara", "Schinken-Sahnesauce, Ei", "12,40"),
        ("73", "Marinara", "Tomatensauce und Meeresfrüchte", "17,10"),
        ("74", "Ajo con Aceite", "natives Olivenöl, frische Tomaten, Knoblauch, Peperoni", "13,60"),
        ("75", "Collo", "Lassen Sie sich überraschen.", "14,80"),
        ("76", "Espinacas con Gambas", "Sahnesauce, Gambas, Spinat, Peperoni", "16,50"),
        ("77", "Gorgonzola", "Sahnesauce, Gorgonzola, Spinat, Pilze", "15,90"),
    ]),
    ("penne", "Penne", None, None, [
        ("80", "Diabolo", "Tomaten-Sahnesauce, Paprika, Cherrytomaten, Peperoni", "13,60"),
        ("81", "Al Salmon", "Tomaten-Sahnesauce, Lachs, Cherrytomaten", "17,10"),
        ("82", "Rocco", "Tomaten-Sahnesauce, Thunfisch, Pilze, Cherrytomaten", "16,50"),
        ("83", "Collo", "Tomaten-Sahnesauce, Lachs, Cherrytomaten, Brokkoli, Zucchini", "17,10"),
        ("84", "Tomate con Mozzarella", "Tomaten-Sahnesauce, Mozzarella, Cherrytomaten, leicht pikant", "15,90"),
        ("85", "Steinpilze und Hähnchenbrust", "Tomatensauce, Zucchini, Steinpilze, Hähnchenbrust, Cherrytomaten", "17,10"),
        ("86", "Filetspitzen", "Tomaten-Sahnesauce, Schweinefilet, Zucchini, getrocknete Tomaten", "17,10"),
        ("87", "Rinderroastbeef", "Tomatensauce, Roastbeef, Pilze, Rucola, Zucchini, Cherrytomaten", "18,30"),
    ]),
    ("roastbeef", "Roastbeef", "Vom Grill.", "Dazu servieren wir einen kleinen Salat und unser selbstgebackenes Brot.", [
        ("90", "a la Brasa", "mit Kräuterbutter", "28,30"),
        ("91", "al Pepe Verde", "mit selbstgemachter Pfeffersauce", "31,30"),
        ("92", "Primavera", "mit frischen Tomaten und Knoblauch", "31,30"),
        ("93", "con Champiñones y Cebollas", "mit Champignons und roten Zwiebeln", "31,30"),
        ("94", "Sevillano", "mit Serranoschinken umwickelt, mit frischen Tomaten", "32,50"),
    ]),
    ("filets", "Hähnchen & Schwein", None, "Dazu servieren wir einen kleinen Salat und unser selbstgebackenes Brot.", [
        ("100", "Pechuga de Pollo a la Plancha", "gegrilltes Hähnchenbrustfilet", "19,50"),
        ("101", "Pechuga de Pollo Empanada", "Hähnchenbrustfiletstücke in Bierpanade, mit selbstgemachter Honigsenfsauce", "22,50"),
        ("102", "Solomillo de Cerdo a la Plancha", "gegrilltes Schweinefilet mit Kräuterbutter", "19,50"),
        ("103", "Solomillo con Champiñones", "gegrilltes Schweinefilet in selbstgemachter Champignon-Sahnesauce", "21,80"),
        ("104", "Solomillo al Roquefort", "gegrilltes Schweinefilet in selbstgemachter Gorgonzolasauce", "21,80"),
        ("105", "Solomillo en Salsa de Pimienta", "gegrilltes Schweinefilet in selbstgemachter Pfeffersauce", "21,80"),
    ]),
    ("fisch", "Fisch", None, "Dazu servieren wir einen kleinen Salat, Alioli und unser selbstgebackenes Brot.", [
        ("114", "Calamares a la Plancha", "gegrillte Calamares", "16,50"),
        ("115", "Calamares Fritos", "frittierte Calamares", "15,90"),
        ("116", "Gambas a la Plancha", "gegrillte Gambas", "17,10"),
        ("117", "Boquerones Fritos", "frittierte Sardellen", "15,30"),
        ("118", "Muslitos de Mar", "frittierte Krebsscheren", "15,90"),
        ("119", "Dorada a la Plancha", "gegrilltes Doradenfilet auf spanischen Kartoffeln", "22,40"),
        ("120", "Sardinas a la Plancha", "gegrillte Sardinen", "18,30"),
    ]),
    ("beilagen", "Beilagen", None, "Beilagen servieren wir ausschließlich zu Rind-, Schwein-, Hähnchen- und Fischgerichten.", [
        ("125", "Bratkartoffeln", "mit Serrano und roten Zwiebeln", "5,80"),
        ("126", "Gebackene Kartoffel", "mit Kräuterquark und Alioli", "6,50"),
        ("127", "Gebratenes Gemüse", "mediterran gewürzt, mit Parmesan", "7,70"),
    ]),
]
